service: vgames-thumbnail-ms

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  timeout: 10
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"          
          Resource: arn:aws:s3:::${self:custom.gamesBucket.name}/*
  environment:
    TIMG_HSIZE: "166"
    TIMG_WSIZE: "120"
    REGION: ${self:custom.region}

custom:  
  region: ${opt:region, self:provider.region}
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  deletion_policy: Delete
  gamesBucket:
    name: timg-vgameslib-${self:custom.stage}  
  pythonRequirements:    
    dockerizePip: non-linux    

functions:
  s3-thumbnail-generator:
    handler: handler.vgame_timg_generator
    events:
      - s3:
          existing: true
          bucket: !Ref thumbnailBucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpeg
resources:
  Resources:
    thumbnailBucket:
      Type: "AWS::S3::Bucket"      
      Properties:
        BucketName: ${self:custom.gamesBucket.name}

plugins:
  - serverless-python-requirements
